name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: ts_reminder   # <-- Add this line
        run: flutter pub get

      - name: Build APK
        working-directory: ts_reminder   # <-- Add this line
        run: flutter build apk --debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: ts_reminder/build/app/outputs/flutter-apk/app-debug.apk
